# global:
#   resolve_timeout: 5m

# route:
#   receiver: gotify
#   group_by: ['alertname']
#   group_wait: 10s
#   group_interval: 30s
#   repeat_interval: 1h

# receivers:
# - name: gotify
#   webhook_configs:
#   - url: http://gotify:80/message?token=GOTIFY_TOKEN
global:
  resolve_timeout: 1m

route:
  receiver: gotify
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 24h

receivers:
  - name: gotify
    webhook_configs:
      - url: "http://gotify-adapter:5000/alert"
        send_resolved: true
