global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "environment_exporter"
    static_configs:
      - targets:
          - exporter:9100

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

